name: Run Tests
on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths-ignore:
      - "README.md"
  release:
    types: [created]
  workflow_dispatch:

permissions:
  id-token: write # This is required for requesting the JWT for OIDC
  contents: read # This is required for actions/checkout

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: "./go.mod"
        id: go

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: Setup atmos
        uses: cloudposse/github-action-setup-atmos@v2
        with:
          install-wrapper: false

      - name: Get dependencies
        run: go mod download

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::799847381734:role/cptest-test-gbl-sandbox-tester
          role-session-name: githubaction-test-repo-terratest-helpers
          aws-region: us-east-2

      - name: Run tests
        run: |
          go test ./...
